### PR TITLE
Firefox/rc/0.23.0 - #46 Port to FireFox? 

### PR DESCRIPTION
**Pull request by clfer**
Hi @sylouuu 

Here is a release candidate for a Firefox compatible version of this module.
As Firefox has done its transition to WebExtensions, it is now mostly compatible with chrome extensions. (They even declared the chrome.* namespace to make the transition easier)

I made the needed adjustment and the extension is now fully functional on both browser.
The only functionality that I had to change was the contextual menu shortcut and I tried to improve it on the way.

Mitigation:
 - Only tested on last browsers version (Chrome 64 & Firefox 58)
 - No idea of the full process of publishing an extension on Firefox. I followed the [guideline](https://developer.mozilla.org/fr/Add-ons/Distribution) to generate a [signed version](https://github.com/clfer/chrome-tab-modifier/raw/de52a77d5befc59f0ef23d6c7969f7f67590caab/dist/web-ext-artifacts/tab_modifier-0.21.0.xpi) but I don't really want to take all the credit and publish it under my name. How do you want to proceed?

Waiting for your feedback 

Have a good night

### CODE REVIEW

**Comment by sylouuu** [comment]
Hey @clfer 

You have worked hard on the Firefox port. The result is pretty nice, I noticed few things:

* After selecting manifest.json in FF to try the extension, I can see a warning "Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page."
* The export rules feature in the settings page does not work (try it)
* When I check the console from the Options page I can see:

```
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« script-src moz-extension://9af7b228-6819-3546-b8d6-41bdc6443034 https://ajax.googleapis.com https://www.google-analytics.com »). Source: call to eval() or related function blocked by CSP.
angular.js:1124:20
Erreur d’analyse XML : mal formé
Emplacement : file:///Users/syl/Sites/perso/chrome-tab-modifier/dist/html/tab_rules.html
Numéro de ligne 3, Colonne 110 :
tab_rules.html:3:110
Erreur d’analyse XML : erreur de syntaxe
Emplacement : file:///Users/syl/Sites/perso/chrome-tab-modifier/dist/js/icons.min.json
Numéro de ligne 1, Colonne 1 :
```

Otherwise the core features are OK!

Best

**Comment by clfer** [comment]
Thanks for the feedbacks

I will take a look at the point that you mentioned and come back to you.

Of what i understand, the first one is just a warning of an ignored key: background.persistent is [not yet supported](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/background) by Firefox while it is [used in Chrome](https://developer.chrome.com/extensions/event_pages)

I will check the other one later

Have a good day

**Comment by clfer** [comment]
To add on the background.persistent warning, ABP has the same message:

abp_firfox_background_persistent_warning

I think it must be OK like this

**Comment by clfer** [comment]
@sylouuu I can't reproduce the 2 other bugs.
What Firefox/Chrome version are you using for the tests?
Is there anything particular about the rules you are trying to export?

**Review by syl-oh — APPROVED** [review]

**Comment by sylouuu** [comment]
Hi @clfer,

The entire code base has been rewritten. If this is still needed, can you contribute again? Tab Modifier 1.0 is now available!

Feel free to open a new PR,

Bests

**Pull request closed without merging**
