### PR TITLE
Changes script interaction to support SPAs

### LINKED ISSUE #64: Problem with Slack
Great extension, thanks!!

My issue is with Slack -- I have a rule to append `•wh•` to all my tabs, and this is the result:

image

(The rule is match any and use `{title}•wh•`)

### LINKED ISSUE #93: Allow tab names to change based on SPA url route changes
Many SPA (Single Page Apps) dont refresh the page and only change a fragment of the URL to navigate within the application.

e.g. 
https://myurl.com/page#sectionone 
https://myurl.com/page#sectiontwo

I would like to be able to change tab title in this situation where as you navigate through web app only the sectionone/two part is changing.

### LINKED ISSUE #105: Flaky behavior on Asana
**Browser:** `Chrome`
**Extension version:** 0.20.0

### Expected behavior

Icon is same when I navigate to a url within a single page app and when I refresh the page

### Actual behavior

http://recordit.co/2dihxjfzwm

At second 10-11 I use the SPA navigation and the icon changes to the proper one but then changes back immediately to the previous one. When I refresh the page with that URL, the proper icon is loaded

### Steps to reproduce the behavior

I added two URLs to the rules, the url for "My Tasks" and for "Home". Then I load each page in asana SPA navigation or try by reloading

### LINKED ISSUE #110: Return blank when an element doesn't exist
I'm wanting to put the main heading of a page (of a certain website) in the title.
Usually this will be h1 but sometimes h2 has been used instead.

So the rule for my title looks something like this:
{div.[name] h1} {div.[name] h2}

(where [name] is the name of a valid class)

What's happening is if h1 doesn't exist but h2 does, the title looks like:
{div.[name] h1} [value of h2]

And if h1 exists but h2 doesn't, the title looks like:
[value of h1] {div.[name] h2}

What I'd like is to display a blank if h1 or h2 doesn't exist, instead of the rule.
That way, it would either be:
[value of h1] [blank]
or
[blank] [value of h2]

Is this possible?

### LINKED ISSUE #112: Title Manipulation
Currently I am trying to use regex to manipulate the title for youtube.com. When the user has a notification the title of the page is '(1) Youtube' for example. I currently have: ^.*?\([^\d]*\d+[^\d]*\).*$
This matches the parentheses, but when the notification is gone, the title becomes 'YouTube'. When using the above regex, the title become @1 when there is not a match. How can I handle this to make it blank when there is no '(1)' in the title? Thanks!

### LINKED ISSUE #159: Allow for fallback/optional title manipulation
It would be great if you could specify that parts of the title are optional or have some sort of default value if not specified. This is usefull for rules that match websites that return a mixed set of pages (in my case, HTML and JSON).

This is what I'm currently looking at:
screenshot 2018-09-10 13 31 09

I'd like to suggest the following syntax:
- `{title|"Untitled"}` (this will also allow for "optional" selectors, since you can specify an empty string as a fallback)
- `{title|$default}` (will use the default title that Chrome uses)

Awesome plugin by the way! 🌟

### LINKED ISSUE #168: Intermittent issues when page dynamically updates title
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

### Tab Modifier version

**Browser:** `Chrome`
**Extension version:** `0.22.0`

### Expected behavior
The rule to be applied

### Actual behavior
Showing e.g. @1 instead

### Steps to reproduce the behavior
Create a rule in e.g. JIRA and do some updates. Sometimes the placeholder (@1) is shown instead of the rule output

image

image

### LINKED ISSUE #185: Why use WebKitMutationObserver?
Hello @sylouuu 
why do you use ``window.WebKitMutationObserver`` to observe favicon and title changes, when you could use ``chrome.tabs.onUpdated`` listener instead? This is so much simpler and resource efficient.

### PR DESCRIPTION
**Pull request by MartinLichtblau**
@sylouuu I auto formatted the code and created some unnecessary changes. I also didnt't know whether the /dist needs to be generated from the /src when only the content and backround script changed; so I just copied it by hand. So this closes #185 (my isssue)
Since it works with SPAs now it fixes #168 fixes #168 fixes #105 fixes #93 fixes #64 
Related fixes 
- title isn't changed if dom selector not found: thus fixes #159 fixes #112 fixes #110
Could fix:
#177 #158

### CODE REVIEW

**Comment by MartinLichtblau** [comment]
@sylouuu What do you think of that commit? I think others would benefit from it.

**Comment by MartinLichtblau** [comment]
Hey @sylouuu to remind you to accept this Pull Request.

**Comment by MartinLichtblau** [comment]
Gooood morning @sylouuu !!! :_D Any plans to accept this Pull Request?

**Comment by sylouuu** [comment]
Hi @MartinLichtblau 

Thanks for your work. As I said in https://github.com/sylouuu/chrome-tab-modifier/issues/180 I have no plan to work on TM at the moment. Even if I merge this, I won't release a new version, etc.

Thanks for your understanding!

**Comment by sylouuu** [comment]
Hi @MartinLichtblau,

The entire code base has been rewritten. If this is still needed, can you contribute again? Tab Modifier 1.0 is now available!

Feel free to open a new PR,

Bests

**Pull request closed without merging**
