### PR TITLE
Support all symbols in title when regexp matching

### PR DESCRIPTION
**Pull request by lionsoft**

### CODE REVIEW

**Comment by sylouuu** [comment]
Hi @lionsoft,

Please provide here the use case and the before/after.

Bests

**Comment by lionsoft** [comment]
Sample URL: *http://example.com?__title=Пример
<http://example.com?__title=%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80>*
URL Mather: *__title=([^&]+)*

Еxpected result: *Пример*
Actual result: *%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80*


вс, 9 июн. 2024 г. в 10:28, Syl ***@***.***>:

**Comment by sylouuu** [comment]
Please add corresponding unit tests. It's already set-up, just take a look how it works.

Regards

**Comment by sebastienfontaine** [comment]
https://github.com/furybee/chrome-tab-modifier/pull/307

**Pull request closed without merging**
